import type { AuditReport, Finding, Severity, Status } from '../types.js';
import type { MaturityProfile } from '../engine/maturity.js';

const TAG: Record<Status, string> = {
  PASS: '✅',
  FAIL: '🔴',
  WRONG: '⚠️',
  MISSING: '🚫',
  DEPRECATED: '💀',
  EXPERIMENTAL: '🧪',
  UNKNOWN: '❓',
  NOT_APPLICABLE: '➖',
};

const SEV_TAG: Record<Severity, string> = {
  CRITICAL: '🔴',
  HIGH: '🟠',
  MEDIUM: '🟡',
  LOW: '🟢',
  FUTURE: '🔵',
};

const SEV_NAME: Record<Severity, string> = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  FUTURE: 'FUTURE',
};

const STATUS_NAME: Record<Status, string> = {
  PASS: 'GOOD',
  FAIL: 'FAIL',
  WRONG: 'WRONG',
  MISSING: 'MISSING',
  DEPRECATED: 'DEPRECATED',
  EXPERIMENTAL: 'EXPERIMENTAL',
  UNKNOWN: 'NEEDS REVIEW',
  NOT_APPLICABLE: 'SKIPPED',
};

/** Renders the Section 14 report template from USAT.md. */
export function renderMarkdown(report: AuditReport, profile: MaturityProfile): string {
  const out: string[] = [];
  const p = (line = '') => out.push(line);

  const findings = report.findings;
  const active = findings.filter((f) => !f.suppressedReason);
  const suppressed = findings.filter((f) => Boolean(f.suppressedReason));
  const unresolved = active.filter((f) => f.status === 'UNKNOWN');
  const actioned = active.filter((f) => f.status !== 'PASS' && f.status !== 'UNKNOWN');
  const passed = active.filter((f) => f.status === 'PASS');

  p('# 🔍 Universal Software Audit Report');
  p();
  p(`> Generated by **USAT** · schema \`${report.schema}\``);
  p();
  p('| | |');
  p('|---|---|');
  p(`| **Project** | \`${report.target.name}\` |`);
  p(`| **Path** | \`${report.target.path}\` |`);
  if (report.target.repoUrl) p(`| **Repository** | ${report.target.repoUrl} |`);
  p(
    `| **Commit** | ${report.target.commit ? `\`${report.target.commit.slice(0, 8)}\`` : 'n/a'} (${report.target.ref ?? 'detached'}) |`,
  );
  p(`| **Date** | ${report.generatedAt} |`);
  p(`| **USAT version** | ${report.usatVersion} |`);
  p(`| **Detected type** | ${humanList(report.detection.projectTypes) || 'unclassified'} |`);
  p(`| **Platform** | ${humanList(report.detection.platforms) || 'unclassified'} |`);
  p(
    `| **Stack** | ${humanList([...report.detection.languages, ...report.detection.frameworks])} |`,
  );
  p(
    `| **Maturity** | ${profile.label}${report.options.profile === 'auto' ? ' *(auto-detected)*' : ' *(forced)*'} |`,
  );
  p(`| **Depth** | ${report.options.depth} |`);
  p();

  /* ------------------------------------------------------------- summary -- */
  p('## 📊 Executive Summary');
  p();
  const band = report.score.expectedBand;
  const coverage = report.score.automationCoverage;
  const queue = report.score.counts.UNKNOWN ?? 0;
  p(`### Overall Health Score: **${report.score.overall}/100**`);
  p();
  p(`${bar(report.score.overall, 100)}`);
  p();
  p(
    `Verified automatically: **${fmt(coverage)}%** of applicable checks. ` +
      `${queue} check${queue === 1 ? '' : 's'} need a human — see the judgement queue.`,
  );
  p();
  if (coverage < 60) {
    p(
      `> ⚠️ **Read this score as a floor, not a grade.** Only ${fmt(coverage)}% of applicable ` +
        `checks could be resolved without a human. The unverified ${100 - Math.round(coverage)}% ` +
        `is not "passing" — it is unknown, and it is excluded from the arithmetic above rather ` +
        `than counted as credit.`,
    );
    p();
  }
  p(
    `Expected band for **${profile.label}**: ${band[0]}–${band[1]} — ${verdict(report.score.overall, band)}`,
  );
  p();
  if (profile.summary) p(`> ${profile.summary.trim()}`);
  p();

  p('| Dimension | Score | Confidence |');
  p('|---|---|---|');
  for (const s of report.score.sections) {
    // A section can score 10/10 on one verified rule out of six. Mark it, so a
    // perfect-looking table does not imply a thorough audit.
    const thin = s.score !== null && s.confidence < 50 ? ' †' : '';
    p(
      s.score === null
        ? `| ${s.id} · ${s.title} | — not verified | 0% |`
        : `| ${s.id} · ${s.title} | ${fmt(s.score)}/10${thin} | ${fmt(s.confidence)}% |`,
    );
  }
  p();
  p(
    `*Confidence = share of applicable rules the engine could verify automatically; ` +
      `unverified checks are excluded from the score rather than counted as passes. ` +
      `**†** = fewer than half of that section's applicable checks could be verified. ` +
      `Automation coverage: **${fmt(coverage)}%**. The rest is in the judgement queue below.*`,
  );
  p();

  /* -------------------------------------------------------------- counts -- */
  p('## 🏷️ Findings Summary');
  p();
  p('| Status | Count | | Severity (open findings) | Count |');
  p('|---|--:|-|---|--:|');
  const statusRows: Status[] = [
    'PASS',
    'FAIL',
    'WRONG',
    'MISSING',
    'DEPRECATED',
    'EXPERIMENTAL',
    'UNKNOWN',
  ];
  const sevRows: Severity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'FUTURE'];
  for (let i = 0; i < Math.max(statusRows.length, sevRows.length); i++) {
    const st = statusRows[i];
    const sv = sevRows[i];
    const left = st
      ? `${TAG[st]} ${STATUS_NAME[st]} | ${report.score.counts[st] ?? 0} |`
      : '  |  |';
    const right = sv
      ? `${SEV_TAG[sv]} ${SEV_NAME[sv]} | ${report.score.severityCounts[sv] ?? 0} |`
      : '  |  |';
    p(`| ${left} : | ${right}`);
  }
  p();
  if (suppressed.length > 0) {
    p(
      `*${suppressed.length} finding(s) suppressed by project policy — see [Accepted risk](#-accepted-risk-suppressions).*`,
    );
    p();
  }

  /* ------------------------------------------------------------ immediate -- */
  p('## 🚨 Immediate Action Required');
  p();
  const urgent = actioned
    .filter((f) => f.severity === 'CRITICAL' || f.severity === 'HIGH')
    .slice(0, 15);
  if (urgent.length === 0) {
    p('No CRITICAL or HIGH findings. Nice.');
    p();
  } else {
    urgent.forEach((f, i) => {
      const loc = primaryLocation(f);
      p(`${i + 1}. ${SEV_TAG[f.severity]} **${f.title}** · \`${f.ruleId}\``);
      p(`   - **Where:** ${loc}`);
      p(`   - **Why:** ${f.message}`);
      if (f.remediation) p(`   - **Fix:** ${f.remediation}`);
    });
    p();
  }

  /* ----------------------------------------------------------- by section -- */
  p('## 📁 Section-by-Section Findings');
  p();
  const sectionMeta = new Map(report.score.sections.map((s) => [s.id, s]));
  const bySection = groupBy(actioned, (f) => f.section);
  const sectionIds = [...new Set([...report.score.sections.map((s) => s.id), ...bySection.keys()])];
  sectionIds.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  for (const id of sectionIds) {
    const meta = sectionMeta.get(id);
    const items = bySection.get(id) ?? [];
    const good = passed.filter((f) => f.section === id);
    const title = meta?.title ?? items[0]?.sectionTitle ?? id;
    p(`### ${id} · ${title}`);
    p();
    if (meta) {
      p(
        meta.score === null
          ? `**Not automatically verifiable** · ` +
              `${meta.applicable} applicable rule(s), all requiring judgement.`
          : `**Score ${fmt(meta.score)}/10** · ${bar(meta.score, 10)} · ` +
              `${meta.passed} passed / ${meta.failed} open / ${meta.unknown} to review`,
      );
      p();
    }
    if (items.length === 0) {
      p('No open findings in this section. ✅');
      p();
      continue;
    }
    for (const f of items.sort(severityOrder)) {
      p(`- ${TAG[f.status]} **${f.title}** \`${f.ruleId}\` — ${f.message}`);
      if (f.locations.length > 0) {
        p(
          `  - 📍 ${f.locations.slice(0, 4).map(fmtLocation).join(', ')}${f.locations.length > 4 ? ` (+${f.locations.length - 4})` : ''}`,
        );
      }
      if (f.dampened) {
        p(`  - 🪶 Downgraded ${f.baseSeverity} → ${f.severity} by the ${profile.label} profile`);
      }
      if (f.remediation) p(`  - 🛠️ ${f.remediation}`);
      if (f.references?.length) p(`  - 📚 ${f.references.join(' · ')}`);
    }
    if (good.length > 0) {
      p();
      p(`<details><summary>${good.length} check(s) passing in ${id}</summary>`);
      p();
      for (const f of good) p(`- ✅ ${f.title} \`${f.ruleId}\``);
      p();
      p('</details>');
    }
    p();
  }

  /* ------------------------------------------------------------- judgement */
  p('## 🧠 Judgement Queue (agent / human review)');
  p();
  p('These checks cannot be settled by grep. Work through them with an agent or a reviewer;');
  p('each one records the evidence required. **RULE 4: never mark ✅ without evidence.**');
  p();
  if (unresolved.length === 0) {
    p('Nothing pending — every applicable rule was resolved automatically.');
    p();
  } else {
    p('| Rule | Section | Severity | What to look for | Evidence to record |');
    p('|---|---|---|---|---|');
    for (const f of unresolved) {
      p(
        `| \`${f.ruleId}\` ${escapeCell(f.title)} | ${f.section} | ${SEV_TAG[f.severity]} ${f.severity} | ` +
          `${escapeCell(f.why ?? f.message)} | ${escapeCell(f.evidenceHint ?? 'file:line + reasoning')} |`,
      );
    }
    p();
  }

  /* ------------------------------------------------------------ suppressed */
  if (suppressed.length > 0) {
    p('## 🤝 Accepted Risk (suppressions)');
    p();
    p('| Rule | Severity | Reason |');
    p('|---|---|---|');
    for (const f of suppressed) {
      p(
        `| \`${f.ruleId}\` ${escapeCell(f.title)} | ${SEV_TAG[f.severity]} ${f.severity} | ${escapeCell(f.suppressedReason ?? '')} |`,
      );
    }
    p();
  }

  /* --------------------------------------------------------------- roadmap */
  p('## 🗺️ Recommended Roadmap');
  p();
  const sprint0 = actioned.filter(
    (f) => f.severity === 'CRITICAL' || (f.severity === 'HIGH' && f.ruleClass === 'security'),
  );
  const sprint1 = actioned.filter(
    (f) => f.severity === 'HIGH' && !(f.severity === 'HIGH' && f.ruleClass === 'security'),
  );
  const sprint2 = actioned.filter((f) => f.severity === 'MEDIUM');
  const backlog = actioned.filter((f) => f.severity === 'LOW' || f.severity === 'FUTURE');

  roadmapBlock(p, 'SPRINT 0 · now', 'Stop the bleeding. Ship before anything else.', sprint0);
  roadmapBlock(p, 'SPRINT 1 · next 1–2 weeks', 'Close the remaining HIGH-severity debt.', sprint1);
  roadmapBlock(
    p,
    'SPRINT 2 · next month',
    'MEDIUM gaps — schedule them or they never happen.',
    sprint2,
  );
  roadmapBlock(p, 'BACKLOG', 'LOW and FUTURE items. Re-read after the next audit.', backlog);

  if (profile.focus.length > 0) {
    p(`### 🎯 What actually matters at **${profile.label}**`);
    p();
    for (const f of profile.focus) p(`- ${f}`);
    p();
  }
  if (profile.defer.length > 0) {
    p('<details><summary>Deliberately deferred at this stage</summary>');
    p();
    for (const d of profile.defer) p(`- ~~${d}~~`);
    p();
    p('</details>');
    p();
  }

  /* ------------------------------------------------------------- appendix -- */
  p('## 🧾 Appendix');
  p();
  p('<details><summary>Detection facts</summary>');
  p();
  p('```yaml');
  p(`maturity: ${report.detection.maturity}`);
  p(`languages: [${report.detection.languages.join(', ')}]`);
  p(`frameworks: [${report.detection.frameworks.join(', ')}]`);
  p(`package_managers: [${report.detection.packageManagers.join(', ')}]`);
  p(`databases: [${report.detection.databases.join(', ')}]`);
  p(`platforms: [${report.detection.platforms.join(', ')}]`);
  p(`flags: [${report.detection.flags.join(', ')}]`);
  p('metrics:');
  for (const [k, v] of Object.entries(report.detection.metrics)) p(`  ${k}: ${v}`);
  p('```');
  p();
  p('Maturity signals:');
  p();
  for (const s of report.detection.maturitySignals) p(`- ${s}`);
  p();
  p(
    `Rule packs loaded (${report.options.packsLoaded.length}): ${report.options.packsLoaded.join(', ') || 'none'}`,
  );
  p();
  p(
    `Rule packs skipped as not applicable (${report.options.packsSkipped.length}): ${report.options.packsSkipped.join(', ') || 'none'}`,
  );
  p();
  p('</details>');
  p();
  p('---');
  p();
  p(
    '<sub>Report generated by USAT — the Universal Software Audit Template. ' +
      'Scores are reproducible: re-run with the same rules and depth to compare. ' +
      'USAT checks process and code hygiene; it is not a penetration test.</sub>',
  );
  p();

  /* -------------------------------------------------------------- trailer -- */
  p(TRAILER_BEGIN);
  p('```yaml');
  p(trailer(report));
  p('```');
  p(TRAILER_END);
  p();

  return out.join('\n');
}

/* --------------------------------------------------------------- helpers -- */

function roadmapBlock(
  p: (s?: string) => void,
  title: string,
  blurb: string,
  items: Finding[],
): void {
  p(`### ${title}`);
  p();
  p(`*${blurb}*`);
  p();
  if (items.length === 0) {
    p('Nothing here. ✅');
    p();
    return;
  }
  for (const f of [...items].sort(severityOrder).slice(0, 25)) {
    p(
      `- ${SEV_TAG[f.severity]} \`${f.ruleId}\` ${f.title}${f.remediation ? ` → ${f.remediation}` : ''}`,
    );
  }
  if (items.length > 25) p(`- …and ${items.length - 25} more`);
  p();
}

function severityOrder(a: Finding, b: Finding): number {
  const o: Record<string, number> = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3, FUTURE: 4 };
  return (o[a.severity] ?? 9) - (o[b.severity] ?? 9);
}

export function primaryLocation(f: Finding): string {
  if (f.locations.length === 0) return 'project-wide';
  return f.locations.slice(0, 3).map(fmtLocation).join(', ');
}

function fmtLocation(l: { file: string; line?: number }): string {
  return `\`${l.file}${typeof l.line === 'number' ? `:${l.line}` : ''}\``;
}

function fmt(n: number): string {
  return Number.isInteger(n) ? String(n) : n.toFixed(1);
}

function bar(value: number, max: number, width = 24): string {
  const filled = Math.max(0, Math.min(width, Math.round((value / max) * width)));
  return `\`${'█'.repeat(filled)}${'░'.repeat(width - filled)}\``;
}

function verdict(score: number, band: [number, number]): string {
  if (score >= band[1]) return '**above the expected band** 🎉';
  if (score >= band[0]) return '**within the expected band** 👍';
  if (score >= band[0] - 15) return '**just below the expected band** — close the HIGH findings';
  return '**well below the expected band** — start with SPRINT 0';
}

function humanList(items: string[]): string {
  const uniq = [...new Set(items)];
  if (uniq.length === 0) return '';
  if (uniq.length <= 4) return uniq.join(', ');
  return `${uniq.slice(0, 4).join(', ')} +${uniq.length - 4}`;
}

function groupBy<T>(items: T[], key: (t: T) => string): Map<string, T[]> {
  const m = new Map<string, T[]>();
  for (const item of items) {
    const k = key(item);
    const list = m.get(k) ?? [];
    list.push(item);
    m.set(k, list);
  }
  return m;
}

function escapeCell(s: string): string {
  // Backslashes first: escaping `|` without escaping `\` lets an input
  // backslash turn into an escape for the character that follows it.
  return s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\n/g, ' ').trim();
}

/**
 * Compact, stable YAML used by `usat diff`. Kept in the Markdown on purpose —
 * the report stays a single self-contained artifact you can commit, email, or
 * paste into a PR.
 */
export const TRAILER_BEGIN = '<!-- USAT:TRAILER:BEGIN -->';
export const TRAILER_END = '<!-- USAT:TRAILER:END -->';

export function trailer(report: AuditReport): string {
  const lines: string[] = [];
  lines.push('schema: usat-report-v1');
  lines.push(`generated_at: ${report.generatedAt}`);
  lines.push(`usat_version: ${report.usatVersion}`);
  lines.push(`overall: ${report.score.overall}`);
  lines.push('sections:');
  for (const s of report.score.sections) {
    lines.push(`  ${s.id}: {score: ${s.score}, open: ${s.failed}, review: ${s.unknown}}`);
  }
  lines.push('severity_totals:');
  for (const [k, v] of Object.entries(report.score.severityCounts)) {
    lines.push(`  ${k}: ${v}`);
  }
  lines.push('rules:');
  for (const f of report.findings) {
    lines.push(
      `  ${f.ruleId}: {status: ${f.status}, severity: ${f.severity}, section: ${f.section}}`,
    );
  }
  return lines.join('\n');
}

/** Extracts the machine-readable trailer from a previously rendered report. */
export function parseTrailer(markdown: string): string | null {
  // indexOf + slice rather than /BEGIN([\s\S]*?)END/: the wildcard form is
  // polynomial on input containing many partial BEGIN markers, and this runs
  // on documents supplied by whoever hands us a report.
  //
  // Find the END first and then walk back: a report that *quotes* an earlier
  // BEGIN marker (or one concatenated with a decoy) must still yield its own
  // trailer, so the nearest BEGIN before END is the one that matters.
  const end = markdown.indexOf(TRAILER_END);
  if (end < 0) return null;
  const start = markdown.lastIndexOf(TRAILER_BEGIN, end);
  if (start < 0) return null;
  const body = markdown.slice(start + TRAILER_BEGIN.length, end);

  const fence = /```ya?ml\n/.exec(body);
  if (!fence) return null;
  const yamlStart = fence.index + fence[0].length;
  const yamlEnd = body.indexOf('```', yamlStart);
  return yamlEnd < 0 ? body.slice(yamlStart) : body.slice(yamlStart, yamlEnd);
}
