import fs from 'node:fs';
import { parse as parseYaml } from 'yaml';
import type { Finding, Severity } from '../types.js';
import { parseTrailer } from '../report/markdown.js';
import { isMap } from '../util/yaml.js';

export interface LearnOptions {
  reportPath: string;
  out?: string;
  minSeverity?: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'FUTURE';
  verbose?: boolean;
}

export interface Suggestion {
  id: string;
  title: string;
  section: string;
  sectionTitle: string;
  severity: 'HIGH' | 'MEDIUM' | 'LOW';
  ruleClass: string;
  check: { kind: string; pattern?: string; files?: string[] };
  why: string;
  remediation: string;
  evidence?: string;
  references?: string[];
  triggeredBy: string;
}

const SEVERITY_ORDER: Record<string, number> = {
  CRITICAL: 0,
  HIGH: 1,
  MEDIUM: 2,
  LOW: 3,
  FUTURE: 4,
};

/** Shape of one entry in the compact trailer `rules` mapping. */
interface TrailerRuleInfo {
  section?: string;
  sectionTitle?: string;
  severity?: Severity;
  status?: Finding['status'];
}

function isTrailerRuleInfo(v: unknown): v is TrailerRuleInfo {
  return typeof v === 'object' && v !== null;
}

/**
 * Parse the machine-readable trailer into its YAML mapping. Returns null when
 * there is no trailer or it is not a mapping. The trailer is untrusted input:
 * a malformed one must produce a clear error, not a stack trace.
 */
function parseReportTrailer(reportPath: string): Record<string, unknown> | null {
  const text = fs.readFileSync(reportPath, 'utf8');
  const yamlText = parseTrailer(text);
  if (yamlText === null) return null;
  try {
    const doc: unknown = parseYaml(yamlText);
    return isMap(doc) ? doc : null;
  } catch {
    return null;
  }
}

/** Findings recorded directly in the trailer, if it carries a full array. */
function findingsFromTrailerField(doc: Record<string, unknown>): Finding[] {
  return Array.isArray(doc.findings) ? (doc.findings as Finding[]) : [];
}

/** Compact `rules` mapping → findings-like rows (the common trailer shape). */
function findingsFromTrailerRules(doc: Record<string, unknown>): Finding[] {
  const rules = doc.rules;
  if (!isMap(rules)) return [];
  const out: Finding[] = [];
  for (const [ruleId, raw] of Object.entries(rules)) {
    const info: TrailerRuleInfo = isTrailerRuleInfo(raw) ? raw : {};
    const severity = info.severity ?? 'MEDIUM';
    out.push({
      ruleId,
      title: `Rule ${ruleId}`,
      section: info.section ?? 'S0',
      sectionTitle: info.sectionTitle ?? '',
      severity,
      baseSeverity: severity,
      status: info.status ?? 'UNKNOWN',
      ruleClass: 'maintainability',
      message: `Rule ${ruleId} was ${info.status ?? 'UNKNOWN'}`,
      locations: [],
      why: '',
      remediation: '',
      evidenceHint: 'Manual review required.',
      references: [],
      dampened: false,
      suppressedReason: undefined,
    });
  }
  return out;
}

function logVerbose(options: LearnOptions, findings: Finding[], relevant: Finding[]): void {
  if (!options.verbose) return;
  console.error(`Found ${findings.length} findings in report.`);
  console.error(
    'Statuses:',
    findings
      .map((f) => f.status)
      .filter(Boolean)
      .join(', '),
  );
  console.error(`Found ${relevant.length} relevant findings after filtering.`);
  relevant.forEach((f) => console.error(`  - ${f.ruleId} ${f.status} ${f.severity}`));
}

function groupBySection(findings: Finding[]): Map<string, Finding[]> {
  const bySection = new Map<string, Finding[]>();
  for (const f of findings) {
    const key = f.section || 'S0';
    const group = bySection.get(key);
    if (group) group.push(f);
    else bySection.set(key, [f]);
  }
  return bySection;
}

/** Findings worth acting on: open status AND at/above the severity threshold. */
function selectRelevant(findings: Finding[], minScore: number): Finding[] {
  return findings.filter((f) => {
    if (f.status === 'PASS' || f.status === 'NOT_APPLICABLE') return false;
    if (!f.status) return false;
    return (SEVERITY_ORDER[f.severity] ?? 9) <= minScore;
  });
}

/** Extract findings from the trailer: full `findings` array, else compact `rules`. */
function extractFindings(doc: Record<string, unknown>, verbose: boolean): Finding[] {
  const direct = findingsFromTrailerField(doc);
  if (direct.length > 0) return direct;
  const converted = findingsFromTrailerRules(doc);
  if (verbose && converted.length > 0) {
    console.error(`Converted ${converted.length} rules from trailer.`);
  }
  return converted;
}

export function learnFromReport(options: LearnOptions): Suggestion[] {
  const doc = parseReportTrailer(options.reportPath);
  if (!doc) {
    throw new Error(
      `Could not parse report trailer from ${options.reportPath}. Ensure the report was generated by USA.`,
    );
  }

  const findings = extractFindings(doc, options.verbose ?? false);
  const minScore = SEVERITY_ORDER[options.minSeverity ?? 'MEDIUM'] ?? 2;
  const relevant = selectRelevant(findings, minScore);
  logVerbose(options, findings, relevant);

  const suggestions: Suggestion[] = [];
  let idCounter = 1;
  for (const [section, items] of groupBySection(relevant)) {
    const sectionTitle = items[0]?.sectionTitle ?? section;
    for (const f of items) {
      suggestions.push(generateSuggestion(f, section, sectionTitle, idCounter++));
    }
  }

  return suggestions;
}

function generateSuggestion(
  finding: Finding,
  section: string,
  sectionTitle: string,
  idCounter: number,
): Suggestion {
  const id = `LEARN-${String(idCounter).padStart(3, '0')}`;
  const severity = mapSeverity(finding.severity);
  const ruleClass = finding.ruleClass ?? 'maintainability';

  return {
    id,
    title: finding.title || `Missing check: ${finding.ruleId}`,
    section,
    sectionTitle,
    severity,
    ruleClass,
    check: { kind: 'manual' },
    why:
      finding.why ??
      finding.message ??
      'This requirement was flagged as missing or requiring review.',
    remediation: finding.remediation ?? 'Define and implement the required control.',
    evidence: finding.evidenceHint ?? 'Manual evidence: file:line + reasoning.',
    references: finding.references ?? [],
    triggeredBy: finding.ruleId,
  };
}

function mapSeverity(sev: string): 'HIGH' | 'MEDIUM' | 'LOW' {
  if (sev === 'CRITICAL' || sev === 'HIGH') return 'HIGH';
  if (sev === 'MEDIUM') return 'MEDIUM';
  return 'LOW';
}

export function renderSuggestions(suggestions: Suggestion[]): string {
  const lines: string[] = [];
  lines.push('# =============================================================================');
  lines.push('# GENERATED by `usa learn` — REVIEW REQUIRED before use.');
  lines.push('# This pack contains suggested rules based on gaps found in the audit report.');
  lines.push('# =============================================================================');
  lines.push(`id: learn-suggestions`);
  lines.push(`title: Suggestions from USA Learn`);
  lines.push(`section: S0`);
  lines.push(`section_title: Generated Suggestions`);
  lines.push(`description: >`);
  lines.push(`  These rules were proposed by \`usa learn\` based on the audit findings.`);
  lines.push(`  They are not yet verified; review each and register in rules/index.yaml.`);
  lines.push(`version: '0.1.0-learn'`);
  lines.push('');
  lines.push('rules:');
  for (const s of suggestions) {
    lines.push(`  - id: ${s.id}`);
    lines.push(`    title: ${s.title}`);
    lines.push(`    section: ${s.section}`);
    lines.push(`    section_title: ${s.sectionTitle}`);
    lines.push(`    severity: ${s.severity}`);
    lines.push(`    class: ${s.ruleClass}`);
    lines.push(`    check:`);
    lines.push(`      kind: manual`);
    lines.push(`    why: ${s.why}`);
    if (s.remediation) lines.push(`    remediation: ${s.remediation}`);
    if (s.evidence) lines.push(`    evidence: ${s.evidence}`);
    if (s.references && s.references.length) {
      lines.push(`    references: [${s.references.map((r) => `'${r}'`).join(', ')}]`);
    }
    lines.push(`    # Triggered by: ${s.triggeredBy}`);
    lines.push('');
  }
  return lines.join('\n');
}
