import { stringify as stringifyYaml } from 'yaml';
import fs from 'node:fs';
import path from 'node:path';
import type { Facts } from '../types.js';
import { BOOTSTRAP_CATALOG, type BootstrapCheck, type BootstrapLang } from './catalog.js';

/**
 * Self-extension: USAT auditing stacks it ships no pack for.
 *
 * Detection already names the language (`lang:php`); what is missing is the
 * *rules*. `bootstrapPacks` turns that gap into a starter pack per
 * uncovered language: curated high-signal checks from the catalog, or a
 * clearly-marked generic fallback when the language is unknown even here.
 *
 * Fail-closed by design (see ADR-0012):
 * - Nothing is registered in `rules/index.yaml` automatically.
 * - Every emitted file carries a REVIEW-REQUIRED header.
 * - The CLI prints; it only writes with an explicit `--out`.
 */

export interface BootstrapPack {
  /** e.g. 'stacks/php' — the id the file will carry. */
  packId: string;
  /** e.g. 'stacks/php.yaml' — relative filename for `--out <dir>`. */
  filename: string;
  yaml: string;
}

export interface BootstrapOutcome {
  packs: BootstrapPack[];
  /** Languages already covered by a shipped pack (nothing to do). */
  coveredLangs: string[];
  /** Languages generated from curated catalog entries. */
  generatedLangs: string[];
  /** Languages generated from the generic fallback (extra review needed). */
  fallbackLangs: string[];
  /** Human next-steps, printed after the packs. */
  notes: string[];
}

/** Detected languages with a shipped stack pack — no bootstrap needed. */
const COVERED_LANGS: Record<string, string> = {
  typescript: 'stacks/node-typescript',
  javascript: 'stacks/node-typescript',
  python: 'stacks/python',
  go: 'stacks/go',
  rust: 'stacks/rust',
  java: 'stacks/jvm',
  kotlin: 'stacks/jvm',
  scala: 'stacks/jvm',
  solidity: 'stacks/solidity',
};

export function bootstrapPacks(facts: Facts): BootstrapOutcome {
  const langs = [...facts.flags]
    .filter((f) => f.startsWith('lang:'))
    .map((f) => f.slice('lang:'.length))
    .sort();
  const outcome: BootstrapOutcome = {
    packs: [],
    coveredLangs: [],
    generatedLangs: [],
    fallbackLangs: [],
    notes: [],
  };
  for (const lang of langs) {
    if (COVERED_LANGS[lang]) {
      outcome.coveredLangs.push(lang);
      continue;
    }
    const entry = BOOTSTRAP_CATALOG.find((e) => e.lang === lang);
    outcome.packs.push(entry ? renderCatalogPack(entry) : renderFallbackPack(lang));
    (entry ? outcome.generatedLangs : outcome.fallbackLangs).push(lang);
  }
  outcome.notes = buildNotes(outcome);
  return outcome;
}

const REVIEW_HEADER = `# =============================================================================
# GENERATED by \`usat bootstrap\` — REVIEW REQUIRED before use.
# This pack is a starting proposal, not an audit verdict. Before trusting it:
#   1. Read every pattern. Delete any that misfires on your codebase.
#   2. Audit one project WITH the problem and one WITHOUT it (see
#      CONTRIBUTING.md "Testing a rule"); both runs must behave.
#   3. Add FP/FN regression tests to tests/rules.test.ts.
#   4. Register the reviewed file in rules/index.yaml.
# Until then it stays out of the index and out of every score.
# =============================================================================
`;

function renderCatalogPack(entry: BootstrapLang): BootstrapPack {
  const doc = {
    id: entry.packId,
    title: entry.title,
    section: 'S15',
    section_title: 'Platform-Specific',
    description: `${entry.description} (bootstrap v0.1 — unreviewed)`,
    version: '0.1.0-bootstrap',
    skip_when: { all: [{ fact: `lang:${entry.lang}`, op: 'absent' }] },
    rules: entry.checks.map(renderCheck),
  };
  return {
    packId: entry.packId,
    filename: `${entry.packId}.yaml`,
    yaml: `${REVIEW_HEADER}${stringifyYaml(doc)}`,
  };
}

/** Last resort for languages with no curated knowledge: judgement prompts. */
function renderFallbackPack(lang: string): BootstrapPack {
  const prefix = lang.slice(0, 3).toUpperCase();
  const packId = `stacks/${lang}`;
  const doc = {
    id: packId,
    title: lang,
    section: 'S15',
    section_title: 'Platform-Specific',
    description: `Fallback prompts for ${lang} — USAT has no curated checks for this language yet. Human review carries this pack. (bootstrap v0.1 — unreviewed)`,
    version: '0.1.0-bootstrap',
    skip_when: { all: [{ fact: `lang:${lang}`, op: 'absent' }] },
    rules: [
      {
        id: `${prefix}-001`,
        title: 'Security-sensitive operations reviewed',
        section: 'S15',
        section_title: 'Platform-Specific',
        severity: 'HIGH',
        class: 'security',
        check: { kind: 'manual' },
        why: `No automated ${lang} checks exist yet; dangerous operations need human review.`,
        remediation: `Review ${lang} entry points for injection, auth gaps, and secret handling.`,
        evidence: `File:line of each reviewed sink plus the verdict.`,
      },
      {
        id: `${prefix}-002`,
        title: 'Dependencies and build reviewed',
        section: 'S15',
        section_title: 'Platform-Specific',
        severity: 'MEDIUM',
        class: 'supply-chain',
        check: { kind: 'manual' },
        why: `Dependency pinning and build provenance for ${lang} are unverified.`,
        remediation: 'Pin and lock dependencies; verify the lockfile is committed.',
        evidence: 'Lockfile path, or the decision that none applies.',
      },
    ],
  };
  return { packId, filename: `${packId}.yaml`, yaml: `${REVIEW_HEADER}${stringifyYaml(doc)}` };
}

type BootstrapCheckBuilder = (c: BootstrapCheck) => Record<string, unknown>;

const BOOTSTRAP_CHECK_BUILDERS: Record<BootstrapCheck['kind'], BootstrapCheckBuilder> = {
  grep_wrong: (c) => grepCheck('grep_wrong', c),
  grep_absent: (c) => grepCheck('grep_absent', c),
  grep_present: (c) => grepCheck('grep_present', c),
  grep_deprecated: (c) => grepCheck('grep_deprecated', c),
  file_exists: (c) => ({ kind: 'file_exists', files: c.files ?? [] }),
  manual: () => ({ kind: 'manual' }),
};

function grepCheck(kind: string, c: BootstrapCheck): Record<string, unknown> {
  return {
    kind,
    pattern: c.pattern ?? '',
    include: c.include ?? [],
    ...(c.exclude ? { exclude: c.exclude } : {}),
    flags: 'i',
  };
}

function renderCheck(c: BootstrapCheck): Record<string, unknown> {
  return {
    id: c.id,
    title: c.title,
    section: 'S15',
    section_title: 'Platform-Specific',
    severity: c.severity,
    class: c.ruleClass,
    check: BOOTSTRAP_CHECK_BUILDERS[c.kind](c),
    why: c.why,
    remediation: c.remediation,
    ...(c.evidence ? { evidence: c.evidence } : {}),
    ...(c.references ? { references: c.references } : {}),
  };
}

function buildNotes(outcome: BootstrapOutcome): string[] {
  const notes: string[] = [];
  if (outcome.coveredLangs.length > 0) {
    notes.push(`already covered (no action): ${outcome.coveredLangs.join(', ')}`);
  }
  for (const lang of outcome.generatedLangs) {
    const entry = BOOTSTRAP_CATALOG.find((e) => e.lang === lang)!;
    notes.push(
      `${lang}: curated starter pack generated (${entry.checks.length} checks). ` +
        `Suggested framework detectors next: ${entry.frameworkHints.join('; ')}.`,
    );
  }
  for (const lang of outcome.fallbackLangs) {
    notes.push(
      `${lang}: no curated knowledge — generic judgement prompts generated. ` +
        'Author real checks from this codebase before trusting any score.',
    );
  }
  notes.push(
    'Next: review each file, test against good/bad fixtures, register in rules/index.yaml.',
  );
  return notes;
}

/** Write generated packs: `--out <dir>` for any count, `--out <file>` for one. */
export function writeBootstrapPacks(outcome: BootstrapOutcome, out: string): void {
  if (!out.endsWith('.yaml') && !out.endsWith('.yml')) {
    fs.mkdirSync(out, { recursive: true });
    for (const pack of outcome.packs) {
      fs.writeFileSync(path.join(out, path.basename(pack.filename)), pack.yaml, 'utf8');
    }
    return;
  }
  if (outcome.packs.length !== 1) {
    throw new Error(
      `--out points at a file but ${outcome.packs.length} packs were generated — point --out at a directory instead.`,
    );
  }
  fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
  fs.writeFileSync(out, outcome.packs[0]!.yaml, 'utf8');
}
